# Report 5: Cluster Details for Reactome coherent clusters
  
```{r  echo=FALSE, warning=FALSE, message=FALSE}
  metric_table <- data[['more-spec_table_metrics.txt']]
  library(dplyr)
  library(igraph)
  

#Load files from a metric file
  load_files_tab <- function(data, column_names, path_column, header){
        factor_columns <- match(column_names, names(data))
        factor_combinations <- unique(data[column_names])
        
        for(row in 1:nrow(factor_combinations)){
                combination <- as.vector(t((factor_combinations[row,]))) #extract row AND convert to vector
                check_combination <- data[factor_columns] == combination[col(data[factor_columns])]
                paths <- data[[path_column]][which(apply(check_combination, 1, sum) == length(combination))]
                
                for (file_path in paths){
                  files <- read.table(file_path, sep="\t", header=header, quote="", stringsAsFactors = FALSE)
                    
                  }
                
                }
           return(files)     
        }

  load_files <- function(data, column_names, path_column, header){
        factor_columns <- match(column_names, names(data))
        factor_combinations <- unique(data[column_names])
        
        for(row in 1:nrow(factor_combinations)){
                combination <- as.vector(t((factor_combinations[row,]))) #extract row AND convert to vector
                check_combination <- data[factor_columns] == combination[col(data[factor_columns])]
                paths <- data[[path_column]][which(apply(check_combination, 1, sum) == length(combination))]
                
                for (file_path in paths){
                  files <- read.table(file_path, sep=" ", header=header, quote="", stringsAsFactors = FALSE)
                    
                  }
                
                }
           return(files)     
        }
 

#Function which group different dataframes by Clusters

  #obtain clusters
    group_cluster_information <- function(df1, df2, df3, df4){
      clusters <- unique(df1$Cluster)
      all_clusters <- list()
    
    #for each cluster we obtain a list with clusters information about hpo, funsys and diseases and store it in another list
      for (i in clusters){
        all_groups <- list()

      #filter hpo data frame by cluster
        hp_groups <- filter(df1, Cluster == clusters[i])
        if (nrow(hp_groups) != 0){
          all_groups[["hpo"]] <- hp_groups
        }

      #filter Funsys data frame by cluster and order by coherence score
        reactome_groups <- filter(df2, Cluster == clusters[i])
        if (nrow(reactome_groups) != 0){
          all_groups[["reactome"]] <- reactome_groups
          scores <- reactome_groups$Percentage_of_nodes_with_funsys
          score <- max(scores)
          all_groups[["coherence_score"]] <- score
        }else{
          all_groups[["coherence_score"]] <- 0
        }

      #filter omim data frame by cluster and order by phenotype overlap with diseases
        omim_groups <- filter(df3, Cluster == clusters[i])
        if (nrow(omim_groups) != 0){
          omim_vector_length <- c()
          
          for(omim in 1:length(omim_groups$HPOs_in_clusters)){
            nb <- strsplit(omim_groups$HPOs_in_clusters[omim], ", ")[[1]]
            omim_vector_length[omim] <- length(nb)
          }
          
          omim_index <- with(omim_groups, order(omim_vector_length, decreasing = TRUE))
          omim_groups_ordered <- omim_groups[omim_index,]
          rownames(omim_groups_ordered) <- NULL
          
          all_groups[["omim"]] <- omim_groups_ordered
        }

        name <- paste0("Cluster_", i)
        all_clusters[[name]] <- all_groups 
        }
        return(all_clusters)  
    }

```


## reactome clusters

```{r  echo=FALSE, warning=FALSE, message=FALSE, results='asis'}

  library(kableExtra)

#Load files add add hyperlinks
  
  hpo <- load_files_tab(metric_table, 'Type', 'Cluster_hpo_reactome_0.05', TRUE)
  reactome <- load_files_tab(metric_table, 'Type', 'Cluster_reactome_0.05', TRUE)
  omim <- load_files_tab(metric_table, 'Type', 'Cluster_omim_reactome_0.05', TRUE)

  for (i in 1:length(reactome$Term)){
    url <- paste0("https://reactome.org/content/detail/", reactome$Term[i])
    reactome$Term[i] <- text_spec(reactome$Term[i], link = url)
  }

  for (i in 1:length(hpo$Term)){
    url <- paste0("https://hpo.jax.org/app/browse/term/", hpo$Term[i])
    hpo$Term[i] <- text_spec(hpo$Term[i], link = url)
  }

  for (i in 1:length(omim$Term)){
    omim_id <- unlist(strsplit(omim$Term[i], ":"))
    url <- paste0("https://www.omim.org/entry/", omim_id[2])
    omim$Term[i] <- text_spec(omim$Term[i], link = url)
  }

#clusters_file
  clusters_file_cytoscape <- load_files(metric_table, 'Type', 'cytoscape_file_reactome_0.05', FALSE)
  clusters_file <- clusters_file_cytoscape[,c(1,3,5)]
  colnames(clusters_file) <- c("HPO-A", "HPO-B", "Cluster")

#Group data by cluster

  all_clusters <- group_cluster_information(hpo, reactome, omim)

#Order clusters by coherence score

  length_vector <- c()
  for(i in 1:length(all_clusters)){
    list <- all_clusters[[i]]
    coherence_score <- list[["coherence_score"]]
    length_vector[i] <- coherence_score
    }

  ordered_clusters <- all_clusters[order(length_vector, decreasing=TRUE)]  

#Print Clusters with Coherent Funsys and overlap with diseases

  for(i in 1:length(ordered_clusters)){
    list <- ordered_clusters[[i]]
    cluster_name <- unlist(strsplit(names(ordered_clusters[i]), "_"))
    cluster_number <- cluster_name[2]
    if(!is.null(list[["reactome"]]) & !is.null(list[["omim"]])){
      cat("_ _ _", "\n", "_ _ _", "\n", "_ _ _", "\n")
      list["coherence_score"] <- NULL
      cat("# ", cluster_name, "\n")

      cluster <- subset(clusters_file, Cluster == cluster_number)
      hpo_names <- subset(hpo, Cluster == cluster_number)
      g <- graph.data.frame(cluster, directed = FALSE)
      plot(g, vertex.label=gsub(" ", "\n", hpo_names$Name), vertex.shape="none", vertex.label.cex=c(0.9), vertex.label.color="black")

      for(i in list){
        print(knitr::kable(i, format="markdown"))
        cat("\n")
      }
    }
  }

#Print Clusters with Coherent Funsys 

  for(i in 1:length(ordered_clusters)){
    list <- ordered_clusters[[i]]
    cluster_name <- unlist(strsplit(names(ordered_clusters[i]), "_"))
    cluster_number <- cluster_name[2]
    if(!is.null(list[["reactome"]]) & is.null(list[["omim"]])){
      cat("_ _ _", "\n", "_ _ _", "\n", "_ _ _", "\n")
      list["coherence_score"] <- NULL
      cat("# ", cluster_name, "\n")

      cluster <- subset(clusters_file, Cluster == cluster_number)
      hpo_names <- subset(hpo, Cluster == cluster_number)
      g <- graph.data.frame(cluster, directed = FALSE)
      plot(g, vertex.label=gsub(" ", "\n", hpo_names$Name), vertex.shape="none", vertex.label.cex=c(0.9), vertex.label.color="black")

      for(i in list){
        print(knitr::kable(i, format="markdown"))
        cat("\n")
      }
    }
  }

#Print Clusters which overlap with diseases

  for(i in 1:length(ordered_clusters)){
    list <- ordered_clusters[[i]]
    cluster_name <- unlist(strsplit(names(ordered_clusters[i]), "_"))
    cluster_number <- cluster_name[2]
    if(is.null(list[["reactome"]]) & !is.null(list[["omim"]])){
      cat("_ _ _", "\n", "_ _ _", "\n", "_ _ _", "\n")
      list["coherence_score"] <- NULL
      cat("# ", cluster_name, "\n")

      cluster <- subset(clusters_file, Cluster == cluster_number)
      hpo_names <- subset(hpo, Cluster == cluster_number)
      g <- graph.data.frame(cluster, directed = FALSE)
      plot(g, vertex.label=gsub(" ", "\n", hpo_names$Name), vertex.shape="none", vertex.label.cex=c(0.9), vertex.label.color="black")

      for(i in list){
        print(knitr::kable(i, format="markdown"))
        cat("\n")
      }
    }
  }

  #Print Clusters without Coherent Funsys or overlap with diseases

  for(i in 1:length(ordered_clusters)){
    list <- ordered_clusters[[i]]
    cluster_name <- unlist(strsplit(names(ordered_clusters[i]), "_"))
    cluster_number <- cluster_name[2]
    if(is.null(list[["reactome"]]) & is.null(list[["omim"]])){
      cat("_ _ _", "\n", "_ _ _", "\n", "_ _ _", "\n")
      list["coherence_score"] <- NULL
      cat("# ", cluster_name, "\n")

      cluster <- subset(clusters_file, Cluster == cluster_number)
      hpo_names <- subset(hpo, Cluster == cluster_number)
      g <- graph.data.frame(cluster, directed = FALSE)
      plot(g, vertex.label=gsub(" ", "\n", hpo_names$Name), vertex.shape="none", vertex.label.cex=c(0.9), vertex.label.color="black")
      
      for(i in list){
        print(knitr::kable(i, format="markdown"))
        cat("\n")
      }
    }
  }

```